"""add_unique_constraint_to_marcos_normativos

Revision ID: 40b080b10ece
Revises: c104b960efa2
Create Date: 2026-09-17 14:04:31.948225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40b080b10ece'
down_revision: Union[str, None] = 'c104b960efa2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_marco_nombre_version', 'marcos_normativos', ['nombre', 'version'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_marco_nombre_version', 'marcos_normativos', type_='unique')
    # ### end Alembic commands ###
