"""add_reporte_dominio_and_fuente_ref_id

Revision ID: 9b9490776f20
Revises: 40b080b10ece
Create Date: 2026-09-18 13:04:33.162812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b9490776f20'
down_revision: Union[str, None] = '40b080b10ece'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reporte_dominio',
    sa.Column('reporte_id', sa.Integer(), nullable=False),
    sa.Column('dominio_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dominio_id'], ['dominios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reporte_id'], ['reportes_amenaza.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('reporte_id', 'dominio_id')
    )
    op.add_column('reportes_amenaza', sa.Column('fuente_ref_id', sa.String(length=200), server_default='manual-legacy-1', nullable=False))
    op.alter_column('reportes_amenaza', 'fuente_ref_id', server_default=None)
    op.create_unique_constraint('uq_reporte_fuente_ref', 'reportes_amenaza', ['fuente_ref_id', 'fuente_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_reporte_fuente_ref', 'reportes_amenaza', type_='unique')
    op.drop_column('reportes_amenaza', 'fuente_ref_id')
    op.drop_table('reporte_dominio')
    # ### end Alembic commands ###
