"""crear tablas iniciales del esquema de ciberseguridad

Revision ID: a1a7acb973e7
Revises: 
Create Date: 2026-09-14 16:00:15.709873

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a1a7acb973e7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dominios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_dominios_id'), 'dominios', ['id'], unique=False)
    op.create_table('fuentes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('tipo_confianza', sa.String(length=30), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('fecha_ultima_actualizacion', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_fuentes_id'), 'fuentes', ['id'], unique=False)
    op.create_table('marcos_normativos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marcos_normativos_id'), 'marcos_normativos', ['id'], unique=False)
    op.create_table('tecnicas',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('tactica', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('controles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=30), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('marco_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['marco_id'], ['marcos_normativos.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo', 'marco_id', name='uq_control_marco')
    )
    op.create_index(op.f('ix_controles_id'), 'controles', ['id'], unique=False)
    op.create_table('reglas_deteccion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('formato', sa.String(length=30), nullable=False),
    sa.Column('log_source', sa.String(length=100), nullable=True),
    sa.Column('fuente_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fuente_id'], ['fuentes.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reglas_deteccion_id'), 'reglas_deteccion', ['id'], unique=False)
    op.create_table('reportes_amenaza',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=250), nullable=False),
    sa.Column('fecha_publicacion', sa.Date(), nullable=False),
    sa.Column('contador_incidencias', sa.Integer(), nullable=True),
    sa.Column('fuente_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fuente_id'], ['fuentes.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reportes_amenaza_id'), 'reportes_amenaza', ['id'], unique=False)
    op.create_table('tecnica_dominio',
    sa.Column('tecnica_id', sa.String(length=20), nullable=False),
    sa.Column('dominio_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dominio_id'], ['dominios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tecnica_id'], ['tecnicas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tecnica_id', 'dominio_id')
    )
    op.create_table('tecnica_control',
    sa.Column('tecnica_id', sa.String(length=20), nullable=False),
    sa.Column('control_id', sa.Integer(), nullable=False),
    sa.Column('fuente_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['control_id'], ['controles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fuente_id'], ['fuentes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tecnica_id'], ['tecnicas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tecnica_id', 'control_id')
    )
    op.create_table('tecnica_regla',
    sa.Column('tecnica_id', sa.String(length=20), nullable=False),
    sa.Column('regla_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['regla_id'], ['reglas_deteccion.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tecnica_id'], ['tecnicas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tecnica_id', 'regla_id')
    )
    op.create_table('tecnica_reporte',
    sa.Column('tecnica_id', sa.String(length=20), nullable=False),
    sa.Column('reporte_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['reporte_id'], ['reportes_amenaza.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tecnica_id'], ['tecnicas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tecnica_id', 'reporte_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tecnica_reporte')
    op.drop_table('tecnica_regla')
    op.drop_table('tecnica_control')
    op.drop_table('tecnica_dominio')
    op.drop_index(op.f('ix_reportes_amenaza_id'), table_name='reportes_amenaza')
    op.drop_table('reportes_amenaza')
    op.drop_index(op.f('ix_reglas_deteccion_id'), table_name='reglas_deteccion')
    op.drop_table('reglas_deteccion')
    op.drop_index(op.f('ix_controles_id'), table_name='controles')
    op.drop_table('controles')
    op.drop_table('tecnicas')
    op.drop_index(op.f('ix_marcos_normativos_id'), table_name='marcos_normativos')
    op.drop_table('marcos_normativos')
    op.drop_index(op.f('ix_fuentes_id'), table_name='fuentes')
    op.drop_table('fuentes')
    op.drop_index(op.f('ix_dominios_id'), table_name='dominios')
    op.drop_table('dominios')
    # ### end Alembic commands ###
