"""create vulnerabilidades table and dominio association

Revision ID: c104b960efa2
Revises: a1a7acb973e7
Create Date: 2026-09-15 17:13:05.512064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c104b960efa2'
down_revision: Union[str, None] = 'a1a7acb973e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vulnerabilidades',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('fecha_publicacion', sa.Date(), nullable=False),
    sa.Column('cvss_score', sa.Float(), nullable=True),
    sa.Column('cvss_severity', sa.String(length=20), nullable=True),
    sa.Column('fuente_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fuente_id'], ['fuentes.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vulnerabilidad_dominio',
    sa.Column('vulnerabilidad_id', sa.String(length=50), nullable=False),
    sa.Column('dominio_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dominio_id'], ['dominios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vulnerabilidad_id'], ['vulnerabilidades.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('vulnerabilidad_id', 'dominio_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vulnerabilidad_dominio')
    op.drop_table('vulnerabilidades')
    # ### end Alembic commands ###
