"""create_reglas_traducciones_table

Revision ID: c161ec99040c
Revises: e82f1b4a92c1
Create Date: 2026-10-04 13:52:09.281134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c161ec99040c'
down_revision: Union[str, None] = 'e82f1b4a92c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reglas_traducciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('regla_id', sa.Integer(), nullable=False),
    sa.Column('formato', sa.String(length=30), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('flavor_label', sa.String(length=100), nullable=True),
    sa.Column('target_table', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['regla_id'], ['reglas_deteccion.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('regla_id', 'formato', name='uq_regla_formato_traduccion')
    )
    op.create_index(op.f('ix_reglas_traducciones_id'), 'reglas_traducciones', ['id'], unique=False)
    op.create_index(op.f('ix_reglas_traducciones_regla_id'), 'reglas_traducciones', ['regla_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reglas_traducciones_regla_id'), table_name='reglas_traducciones')
    op.drop_index(op.f('ix_reglas_traducciones_id'), table_name='reglas_traducciones')
    op.drop_table('reglas_traducciones')
    # ### end Alembic commands ###
